name: Do Unit Testing

on:
  pull_request:
    branches:
      - 'using-cicd'
  push:
    branches:
      - 'using-cicd'
jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover
  build-push-docker:
    name: "Build docker dan push to registry"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: 
        docker build -t alfinst/booking_ticket:1.0.0 .
    

